export const fallbackArticlesCs = [
  {
    id: "f1",
    slug: "mechanismus-fungovani-homeopatickych-leku",
    locale: "cs",
    category: "Věda · 2024",
    title: "Mechanismus fungování homeopatických léků vědecky prokázán",
    description: "Nový výzkum přináší přímé důkazy o tom, jak přípravky ovlivňují strukturu vody. Přelomový objev pro celý obor.",
    image: null,
    featured: true,
  },
  {
    id: "f2",
    slug: "kongres-lmhi-bogota-2023",
    locale: "cs",
    category: "Kongres · Bogotá 2023",
    title: "Kongres Mezinárodní homeopatické ligy LMHI",
    description: "",
    image: null,
    featured: false,
  },
  {
    id: "f3",
    slug: "konference-mnichov-2023",
    locale: "cs",
    category: "Konference · Mnichov 2023",
    title: "Mnichovská konference — setkání evropských homeopatů",
    description: "",
    image: null,
    featured: false,
  },
];

export const fallbackArticlesEn = [
  {
    id: "f4",
    slug: "homeopathic-medicines-mechanism-proven",
    locale: "en",
    category: "Science · 2024",
    title: "Mechanism of homeopathic medicines scientifically proven",
    description: "New research provides direct evidence of how preparations affect water structure. A breakthrough discovery for the entire field.",
    image: null,
    featured: true,
  },
  {
    id: "f5",
    slug: "lmhi-congress-bogota-2023",
    locale: "en",
    category: "Congress · Bogotá 2023",
    title: "Congress of the International Homeopathic Medical League LMHI",
    description: "",
    image: null,
    featured: false,
  },
  {
    id: "f6",
    slug: "munich-conference-2023",
    locale: "en",
    category: "Conference · Munich 2023",
    title: "Munich conference — meeting of European homeopaths",
    description: "",
    image: null,
    featured: false,
  },
];

export const fallbackTestimonials = [
  {
    id: "t1",
    nameCs: "Markéta V.",
    nameEn: "Markéta V.",
    textCs: "Po letech s ekzémem jsem konečně našla úlevu. Petra ke mně přistupovala jako k člověku, ne k diagnóze.",
    textEn: "After years with eczema, I finally found relief. Petra treated me as a person, not a diagnosis.",
    detailCs: "ekzém · 3 roky léčby",
    detailEn: "eczema · 3 years of treatment",
    stars: 5,
  },
  {
    id: "t2",
    nameCs: "Jana K.",
    nameEn: "Jana K.",
    textCs: "Přišla jsem kvůli nespavosti a depresím. Výsledky přesáhly moje očekávání — cítím se lépe než roky.",
    textEn: "I came because of insomnia and depression. The results exceeded my expectations.",
    detailCs: "nespavost, deprese",
    detailEn: "insomnia, depression",
    stars: 5,
  },
  {
    id: "t3",
    nameCs: "Tomáš M.",
    nameEn: "Tomáš M.",
    textCs: "Léčíme celou rodinu. Homeopatie nám pomohla tam, kde konvenční medicína selhala.",
    textEn: "We treat the whole family. Homeopathy helped where conventional medicine failed.",
    detailCs: "rodinná péče",
    detailEn: "family care",
    stars: 5,
  },
];
